
export default {
  Change_Page1_text:'Change_Page1_text',
  Change_Page2_text:'Change_Page2_text',
  POPULAR_REFRESH:'POPULAR_REFRESH',
  LOAD_POPULAR_SUCCESS:'LOAD_POPULAR_SUCCESS',
  LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',
  POPULAR_LOADMORE:'POPULAR_LOADMORE',
  POPULAR_LOADMORE_SUCCESS:'POPULAR_LOADMORE_SUCCESS',
  POPULAR_LOADMORE_FAIL:'POPULAR_LOADMORE_FAIL',
}
