
export default {
  Change_Page1_text:'Change_Page1_text',
  Change_Page2_text:'Change_Page2_text',
  POPULAR_REFRESH:'POPULAR_REFRESH',
  POPULAR_REFRESH_SUCCESS:'LOAD_POPULAR_SUCCESS',
  POPULAR_REFRESH_FAIL:'LOAD_POPULAR_FAIL',
  POPULAR_LOADMORE:'POPULAR_LOADMORE',
  POPULAR_LOADMORE_SUCCESS:'POPULAR_LOADMORE_SUCCESS',
  POPULAR_LOADMORE_FAIL:'POPULAR_LOADMORE_FAIL',

  NOTIMESSAGE_REFRESH:'NOTIMESSAGE_REFRESH',
  NOTIMESSAGE_REFRESH_SUCCESS:'NOTIMESSAGE_REFRESH_SUCCESS',
  NOTIMESSAGE_REFRESH_FAIL:'NOTIMESSAGE_REFRESH_FAIL',
  NOTIMESSAGE_LOADMORE:'NOTIMESSAGE_LOADMORE',
  NOTIMESSAGE_LOADMORE_SUCCESS:'NOTIMESSAGE_LOADMORE_SUCCESS',
  NOTIMESSAGE_LOADMORE_FAIL:'NOTIMESSAGE_LOADMORE_FAIL',

}
